services:
  adminer:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./adminer-readonly.php:/var/www/html/index.php:ro
      - /home/ubuntu/FocusLens/Backend/Database_backend:/db
